version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.6
  node: circleci/node@5.3.0
  cloudfront-s3-deploy: trustedshops-public/cloudfront-s3-deploy@3.0.0
  semantic-release: trustedshops-public/semantic-release@6.0.0
  deterministic-zip: timo-reymann/deterministic-zip@1.0.0

anchors:
  deploy_defaults: &deploy_defaults
    attach_workspace: true
    additional_args: "--exclude *.zip"
    remote: /connector/
    pattern: '/connector/*'
    local: build/
    context:
      - connect-team
  filter_only_main: &filter_only_main
    filters:
      branches:
        only: main

commands:
  build_prod:
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - deterministic-zip/install
      - run:
          name: Building App for PROD env and release
          command: |
              yarn build
      - run:
          name: Bundle dist folder to zip archive
          command: |
            cd build/
            deterministic-zip -r connector.zip *

executors:
  node:
    docker:
      - image: cimg/node:21.7-browsers
  python:
    docker:
      - image: cimg/python:3.12.6-browsers

jobs:
  build_qa:
    executor: node
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Building App for QA env
          command: |
              yarn build:qa
      - persist_to_workspace:
          root: .
          paths:
            - .
            - build/
  build_prod:
    executor: node
    steps:
      - build_prod
      - persist_to_workspace:
          root: .
          paths:
            - . 
            - build/
  semantic_release:
    executor: semantic-release/default
    steps:
      - build_prod
      - semantic-release/install
      - semantic-release/execute
  test_e2e:
    executor: python
    steps:
      - attach_workspace:
          at: .
      - browser-tools/install-chrome
      - run:
          name: Install dependencies
          command: npm run test-install
      - run:
          name: Run tests
          command: npm run test
      - store_artifacts:
          path: ./src/tests/results
          destination: test-results
      - store_test_results:
          path: ./src/tests/results

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build_qa:
          filters:
            branches:
              only: /.*/
      - build_prod:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - test_e2e:
          requires:
            - deploy_to_qa
          context:
            - connect-team
      - approve_semantic_release:
          <<: *filter_only_main
          type: approval
          requires:
            - test_e2e
      - semantic_release:
          <<: *filter_only_main
          requires:
            - approve_semantic_release
          context:
            - semantic-release
      - cloudfront-s3-deploy/sync_and_invalidate:
          name: deploy_to_qa
          <<: *deploy_defaults
          <<: *filter_only_main
          bucket_name: ts-connect-qa-trustedshops-app
          distribution_id: E2HC1Y83IARISC
          aws_iam_web_identity_role_arn: $WEB_IDENTITY_ROLE_ARN_QA
          requires:
            - build_qa
      - approve_deploy_to_prod:
          type: approval
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - cloudfront-s3-deploy/sync_and_invalidate:
          name: deploy_to_prod
          <<: *deploy_defaults
          bucket_name: ts-connect-prod-trustedshops-app
          distribution_id: E17P53GJGRBTBG
          aws_iam_web_identity_role_arn: $WEB_IDENTITY_ROLE_ARN_PROD
          requires:
            - build_prod
            - approve_deploy_to_prod
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
