version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.6
  node: circleci/node@5.2.0
  cloudfront-s3-deploy: trustedshops-public/cloudfront-s3-deploy@3.0.0
  semantic-release: trustedshops-public/semantic-release@6.0.0
  deterministic-zip: timo-reymann/deterministic-zip@1.0.0

anchors:
  deploy_defaults: &deploy_defaults
    attach_workspace: true
    additional_args: "--exclude *.zip"
    remote: /connector/
    pattern: '/connector/*'
    local: build/
    context:
      - connect-team
  filter_only_main: &filter_only_main
    filters:
      branches:
        only: main

commands:
  build_prod:
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - deterministic-zip/install
      - run:
          name: Building App for PROD env and release
          command: |
              yarn build
      - run:
          name: Bundle dist folder to zip archive
          command: |
            cd build/
            deterministic-zip -r connector.zip *

executors:
  node:
    docker:
      - image: cimg/node:21.5-browsers

jobs:
  build_qa:
    executor: node
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Building App for QA env
          command: |
              yarn build:qa
      - persist_to_workspace:
          root: .
          paths:
            - .
            - build/
  build_prod:
    executor: node
    steps:
      - build_prod
      - persist_to_workspace:
          root: .
          paths:
            - . 
            - build/
  semantic_release:
    executor: semantic-release/default
    steps:
      - build_prod
      - semantic-release/install
      - semantic-release/execute
  trigger_qa_tests:
    docker:
      - image: cimg/python:3.8
    steps:
      - run:
          name: Trigger QA tests
          command: |
            RESPONSE=$(curl -s -X POST https://circleci.com/api/v2/project/github/trustedshops/test-connect/pipeline \
              --header "Circle-Token: $CIRCLE_CI_TOKEN" \
              --header "Content-Type: application/json" \
              --data '{
                "branch": "main",
                "parameters": {
                  "development_trigger": true,
                  "shop_system": "all",
                  "environment": "QA"
                }
              }')

            PIPELINE_NUMBER=$(echo "$RESPONSE" | grep -o '"number":[0-9]*' | head -1 | sed 's/"number"://')
            echo "Triggered Test Pipeline: https://app.circleci.com/pipelines/github/trustedshops/test-connect/$PIPELINE_NUMBER"

  trigger_prod_tests:
    docker:
      - image: cimg/python:3.8
    steps:
      - run:
          name: Trigger Prod tests
          command: |
            RESPONSE=$(curl -s -X POST https://circleci.com/api/v2/project/github/trustedshops/test-connect/pipeline \
            --header "Circle-Token: $CIRCLE_CI_TOKEN" \
            --header "Content-Type: application/json" \
            --data '{
              "branch": "main",
              "parameters": {
                "development_trigger": true,
                "shop_system": "all",
                "environment": "PROD"
              }
            }')

            PIPELINE_NUMBER=$(echo "$RESPONSE" | grep -o '"number":[0-9]*' | head -1 | sed 's/"number"://')
            echo "Triggered Test Pipeline: https://app.circleci.com/pipelines/github/trustedshops/test-connect/$PIPELINE_NUMBER"               

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build_qa:
          filters:
            branches:
              only: /.*/
      - build_prod:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - approve_semantic_release:
          <<: *filter_only_main
          type: approval
      - semantic_release:
          <<: *filter_only_main
          requires:
            - approve_semantic_release
          context:
            - semantic-release
      - cloudfront-s3-deploy/sync_and_invalidate:
          name: deploy_to_qa
          <<: *deploy_defaults
          <<: *filter_only_main
          bucket_name: ts-connect-qa-trustedshops-app
          distribution_id: E2HC1Y83IARISC
          aws_iam_web_identity_role_arn: $WEB_IDENTITY_ROLE_ARN_QA
          requires:
            - build_qa
      - trigger_qa_tests:
          requires:
            - deploy_to_qa      
      - approve_deploy_to_prod:
          type: approval
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - cloudfront-s3-deploy/sync_and_invalidate:
          name: deploy_to_prod
          <<: *deploy_defaults
          bucket_name: ts-connect-prod-trustedshops-app
          distribution_id: E17P53GJGRBTBG
          aws_iam_web_identity_role_arn: $WEB_IDENTITY_ROLE_ARN_PROD
          requires:
            - build_prod
            - approve_deploy_to_prod
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - trigger_prod_tests:
          requires:
            - deploy_to_prod        
